import Head from 'next/head'
import Image from 'next/image'
import { Outfit } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '700']
})

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <div className={styles.mainArea}>
        <Image src="/image-qr-code.png" alt='qr-code' width={500} height={500} className={styles.image}/>
        <h1 className={`${outfit.className} ${styles.improve}`}>Improve your front-end skills by building projects</h1>
        <p className={`${outfit.className} ${styles.visit}`}>Scan the QR code to visit Frontend Mentor and take your coding skills to the next level</p>
      </div>

    </div>
  )
}
